version: '2'
services:
  mysql8:
    build:
      context: ../mock/mysql
    ports:
      - "3306:3306"
    #      - "33060:33060" # X API
    volumes:
      - ../mock/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: hoge123
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    platform: linux/amd64 # M1 Macの場合
